"""Emit data/processed/bulletins.json -- a compact latest-bulletin feed the
website fetches (client-side, from raw GitHub) to render the "Boletines" news
section. Regenerated by the CI Action whenever a new bulletin lands.

    ante/bin/python build_bulletins_json.py   # or: make news

Shape:
    {
      "generated_utc": "2026-07-15T16:00:00Z",
      "latest_month": "2026-07",
      "previous_month": "2026-06",
      "available_months": ["2001-12", ..., "2026-07"],
      "rows": [   # one per series for latest_month
        {"country","block","category","table","status","raw_value",
         "priority_date","delta_days"}  # delta vs previous month (F→F only)
      ]
    }
delta_days: +avanzó / -retrocedió (movimiento = lo noticiable). null si no comparable.
"""

import json
import os
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd


def _generated_utc(latest_month: str) -> str:
    """Recency stamp for the feed. Defaults to the latest bulletin month (the real
    measure of how fresh the data is — a rebuild from the same bulletins is equally
    fresh), so the artifact is DETERMINISTIC for `dvc repro`. SOURCE_DATE_EPOCH
    (reproducible-builds standard) overrides it if an exact build instant is wanted."""
    epoch = os.environ.get("SOURCE_DATE_EPOCH")
    if epoch:
        return datetime.fromtimestamp(int(epoch), UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    return f"{latest_month}-01T00:00:00Z"


PANEL = Path("data/processed/visa_panel_long.csv")
OUT = Path("data/processed/bulletins.json")


WINDOW = 24  # months of history kept for the selector (bounded so the feed stays small)


def month_rows(cur: pd.DataFrame, prev: pd.DataFrame | None) -> list[dict]:
    """Series rows for one month, with delta_days vs the prior month (F->F only)."""
    out = []
    for k, r in cur.iterrows():
        delta = None
        if prev is not None and r["status"] == "F" and k in prev.index:
            p = prev.loc[k]
            if p["status"] == "F" and pd.notna(r["priority_date"]) and pd.notna(p["priority_date"]):
                delta = int((r["priority_date"] - p["priority_date"]).days)
        out.append(
            {
                "country": k[0],
                "block": k[1],
                "category": k[2],
                "table": k[3],
                "status": r["status"],
                "raw_value": None if pd.isna(r["raw_value"]) else str(r["raw_value"]),
                "priority_date": None if pd.isna(r["priority_date"]) else r["priority_date"].strftime("%Y-%m-%d"),
                "delta_days": delta,
            }
        )
    return out


def main() -> None:
    df = pd.read_csv(PANEL, parse_dates=["bulletin_date", "priority_date"])
    df["ym"] = df["bulletin_date"].dt.strftime("%Y-%m")
    all_months = sorted(df["ym"].unique())
    key = ["country", "block", "category", "table"]
    by_month = {m: g.set_index(key) for m, g in df.groupby("ym")}

    # Keep the last WINDOW months for the selector; each needs its predecessor
    # (even if outside the window) to compute movement.
    window = all_months[-WINDOW:]
    months = {}
    for i, m in enumerate(all_months):
        if m not in window:
            continue
        prev = by_month[all_months[i - 1]] if i > 0 else None
        months[m] = month_rows(by_month[m], prev)

    latest = all_months[-1]
    OUT.write_text(
        json.dumps(
            {
                "generated_utc": _generated_utc(latest),
                "latest_month": latest,
                "available_months": window,  # newest last
                "months": months,
            },
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    print(f"{OUT}: {latest} · {len(months[latest])} series · ventana {len(window)} meses")


if __name__ == "__main__":
    main()
