"""Emit data/processed/bulletins.json -- a compact latest-bulletin feed the
website fetches (client-side, from raw GitHub) to render the "Boletines" news
section. Regenerated by the CI Action whenever a new bulletin lands.

    ante/bin/python build_bulletins_json.py   # or: make news

Shape:
    {
      "generated_utc": "2026-07-15T16:00:00Z",
      "latest_month": "2026-07",
      "previous_month": "2026-06",
      "available_months": ["2001-12", ..., "2026-07"],
      "rows": [   # one per series for latest_month
        {"country","block","category","table","status","raw_value",
         "priority_date","delta_days"}  # delta vs previous month (F→F only)
      ]
    }
delta_days: +avanzó / -retrocedió (movimiento = lo noticiable). null si no comparable.
"""

import json
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd

PANEL = Path("data/processed/visa_panel_long.csv")
OUT = Path("data/processed/bulletins.json")


def main() -> None:
    df = pd.read_csv(PANEL, parse_dates=["bulletin_date", "priority_date"])
    months = sorted(df["bulletin_date"].dt.strftime("%Y-%m").unique())
    latest, previous = months[-1], months[-2]

    key = ["country", "block", "category", "table"]
    cur = df[df["bulletin_date"].dt.strftime("%Y-%m") == latest].set_index(key)
    prev = df[df["bulletin_date"].dt.strftime("%Y-%m") == previous].set_index(key)

    rows = []
    for k, r in cur.iterrows():
        delta = None
        if r["status"] == "F" and k in prev.index:
            p = prev.loc[k]
            if p["status"] == "F" and pd.notna(r["priority_date"]) and pd.notna(p["priority_date"]):
                delta = int((r["priority_date"] - p["priority_date"]).days)
        rows.append(
            {
                "country": k[0],
                "block": k[1],
                "category": k[2],
                "table": k[3],
                "status": r["status"],
                "raw_value": None if pd.isna(r["raw_value"]) else str(r["raw_value"]),
                "priority_date": None if pd.isna(r["priority_date"]) else r["priority_date"].strftime("%Y-%m-%d"),
                "delta_days": delta,
            }
        )

    OUT.write_text(
        json.dumps(
            {
                "generated_utc": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "latest_month": latest,
                "previous_month": previous,
                "available_months": months,
                "rows": rows,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"{OUT}: {latest} · {len(rows)} series · {len(months)} meses")


if __name__ == "__main__":
    main()
